### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by kentcdodds** [hemanth/node-nightly#21]
Hey @hemanth! I heard that this doesn't work on Windows. What needs to happen to get this to work on Windows?

**Comment by tarungarg546** [comment]
Hey i think i can tell you better about it.
I am trying to port it on windows too. Problem with windows seems to be mainly, `kexec` does not support windows so i am using `execa` now instead of `kexec` you can track update here.

Do let me know if this work for you on windows because it does not for me
https://github.com/tarungarg546/node-nightly/tree/windows

**Comment by kentcdodds** [comment]
Oh, if you're having `child_process` issues, you might look at what I've done in `cross-env` to solve that problem :) Basically [I use](https://github.com/kentcdodds/cross-env/blob/8ff5555b0f566cbab4e56ddb5de2416be2959a22/src/index.js#L1) [`cross-spawn`](https://github.com/IndigoUnited/node-cross-spawn) which seems to be working great for the 135k/month downloads it's getting :)
